#!/bin/sh

bri=$(xbacklight -get)

if [[ $bri -lt 15 ]]; then
    icon=""
elif [[ $bri -lt 30 ]]; then
    icon=""
elif [[ $bri -lt 45 ]]; then
    icon=""
elif [[ $bri -lt 60 ]]; then
    icon=""
elif [[ $bri -lt 75 ]]; then
    icon=""
elif [[ $bri -lt 90 ]]; then
    icon=""
else
    icon=""
fi

echo "$icon $bri%"
