#!/bin/sh

vol=$(pamixer --get-volume)
mute=$(pamixer --get-mute)

if [[ $mute == true ]]; then
    icon="ﱝ"
elif [[ $vol -lt 30 ]]; then
    icon="奄"
elif [[ $vol -lt 60 ]]; then
    icon="奔"
else
    icon="墳"
fi

echo "$icon $vol%"
